version: "3.9"
services:
    mysql:
        image: mysql:5.7
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: url_shortener_db
            MYSQL_USER: access
            MYSQL_PASSWORD: abc123
            MYSQL_ROOT_PASSWORD: acc123

    web:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "8080:80"
        command: ["/tmp/wait-for-it.sh", "--timeout=120", "mysql:3306", "--", "bash", "/tmp/db.sh"]
        links:
            - mysql
